### ISSUE TITLE
ruby-based footnotes on your blog are not displayed properly in Firefox

### ISSUE THREAD

**Issue by stof** [tomayac/blogccasion#27]
I'm referring to https://blog.tomayac.com/2021/01/24/ruby-html-footnotes/

![image](https://user-images.githubusercontent.com/439401/105687659-00e7f000-5ef9-11eb-8b9b-64451d459903.png)

Browser: Firefox 84.0.2

Things are working fine in chromium:
![image](https://user-images.githubusercontent.com/439401/105687808-2ffe6180-5ef9-11eb-91d5-272e8278c551.png)

**Comment by tomayac** [comment]
Thanks, this was [reported](https://twitter.com/edent/status/1353427552736579587) yesterday by @edent as well. At this point this is mostly an experiment and I don't advise using it in production. Support seems decent on Blink/WebKit-based browsers, but not so great on Gecko-based browsers like Firefox. I have opened https://github.com/w3c/csswg-drafts/issues/5891 to hear if this even is a valid use case.

**Comment by stof** [comment]
it might be worth adding a note in the article to mention that in a clear way.

**Comment by tomayac** [comment]
Thanks. Done in https://github.com/tomayac/blogccasion/commit/3caf1582ff6d0f34e95a4885fc05c44ef4068cf9. This should go live in the next full hour.
