### ISSUE TITLE
`not all and ${mq}` might not always work

### ISSUE THREAD

**Issue by romainmenke** [tomayac/blogccasion#38]
https://github.com/tomayac/blogccasion/blob/b7d07fff9d910ba632481982fa0bddf1e8586fc9/posts/2019/2019-09-16_not-all-is-nothing-finding-out-if-the-browser-supports-a-given-media-query.md?plain=1#L136

Examples where this string interpolation of media queries would not work as expected :
- `(width) or (height)`
- `only screen`
- `not print`
- `print`
- all variations and more complicated examples of the above

It would only work for `and` separated queries and media queries without a type or modifier:
- `(width)`
- `(width) and (height)`

**Comment by tomayac** [comment]
Thanks for reporting this limitation. Let's discuss it over on https://github.com/w3c/csswg-drafts/issues/5272. Could you post your comment again there? My blog repo is just the "messenger" in this case. I'll be sure to follow the original issue and update my post should a better solution appear.

**Comment by romainmenke** [comment]
Thank you for linking me to the correct issue.
I was following the other one and didn't want to pull it of topic :)
