### ISSUE TITLE
Add social meta tags (og: and twitter:)

### ISSUE THREAD

**Issue by peterpeterparker** [tomayac/blogccasion#5]
Hi Thomas,

If I'm not wrong, except the `twitter:account_id`, the header of your blog posts doesn't contain any social information, is that right?

If so, I would suggest to add some social meta tags to the `<head/>` of your blog posts. Notably the `og:` and `twitter:` tags which will help social network to render nice cards preview of your articles.

Like:

```
<head>
    <meta property="og:description" content="...."/>
    <meta property="og:image" content="https://tomayac.com/...."/>
    <meta property="twitter:card" content="summary"/>
   <!-- ETC. -->
</head>
```

I'm not sure, but actually these might even be used for SEO indexing purpose by Google or so, which could be the cherry on top.

I wish I would have been able to send you a PR but I'm not sure where I should begin.

In your last blog post (https://blog.tomayac.com/2019/09/29/the-redesigned-blogccasion-is-live/) you said that social networks almost killed your blogging, time to fight back 😉 (I'm joking of course)

Best
David

**Comment by tomayac** [comment]
Thanks, definitely on my list! Also schema.org.

**Comment by tomayac** [comment]
Added Facebook, Twitter, and Schema.org markup now. Hope this works.

**Comment by peterpeterparker** [comment]
Cool looks good 👍 

<img width="1185" alt="Capture d’écran 2019-12-03 à 07 26 07" src="https://user-images.githubusercontent.com/16886711/70025740-336cb600-159e-11ea-93fd-606e65071904.png">
